### PR TITLE
Allow SSL and https epg urls

### PR DESCRIPTION
**Pull request by davesayers2014**
Please test on various images before comitting. This works for me on ViX 5.4.001

See here https://github.com/oe-alliance/XMLTV-Import/issues/37

### CODE REVIEW

**Comment by davesayers2014** [comment]
I think this breaks the if has_ipv6 check.

**Comment by jenseneverest** [comment]
Is this plugin even maintained ?? 
Been an issue for a long time, no one is interested.
 i just run a conversion script on my STB.

**Comment by Schimmelreiter** [comment]
> I think this breaks the if has_ipv6 check.

Indeed, it does.
The commit adds additional download code before the **calls** to the original code and returns before invoking it.

The original code for downloading is in "downloadPage" and gets invoked through a call with callback, now the plugin downloads and waits there for the download to finish.
Please consider flaky or slow connections too, so the original call + callback is better.

Its "downloadPage" which needs to be changed, not this function here.

**Comment by Schimmelreiter** [comment]
From a quick glance at the code, only the first line of the change should be enough, as "downloadPage" from Twisted:Web:Client can handle https.
In detail, we might need additional parameters to downloadPage to make https downloads work.

**Comment by davesayers2014** [comment]
Just using `if filename.startswith('http:') or filename.startswith('ftp:') or filename.startswith('https:'):`

Works for some https URLs some give SSL errors

`Log if they need it @alprojuiceking                                                                                                                                                                                                                                                                                                                                          

[EPGImport] download failed: [Failure instance: Traceback: <class 'OpenSSL.SSL.Error'>: [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert handshake failure')]
/usr/lib/enigma2/python/e2reactor.py:184:_doReadOrWrite
/usr/lib/python2.7/site-packages/twisted/internet/tcp.py:243:doRead
/usr/lib/python2.7/site-packages/twisted/internet/tcp.py:249:_dataReceived
/usr/lib/python2.7/site-packages/twisted/protocols/tls.py:315:dataReceived
--- <exception caught here> ---
/usr/lib/python2.7/site-packages/twisted/protocols/tls.py:235:_checkHandshakeStatus
/usr/lib/python2.7/site-packages/OpenSSL/SSL.py:1915:do_handshake
/usr/lib/python2.7/site-packages/OpenSSL/SSL.py:1647:_raise_ssl_error
/usr/lib/python2.7/site-packages/OpenSSL/_util.py:54:exception_from_error_queue
]`

**Comment by davesayers2014** [comment]
If just using `if filename.startswith('http:') or filename.startswith('ftp:') or filename.startswith('https:'):`

Works for some https URLs some give SSL errors

`                                                                                                                                                                                                                                                                                                                                         
[EPGImport] download failed: [Failure instance: Traceback: <class 'OpenSSL.SSL.Error'>: [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert handshake failure')]
/usr/lib/enigma2/python/e2reactor.py:184:_doReadOrWrite
/usr/lib/python2.7/site-packages/twisted/internet/tcp.py:243:doRead
/usr/lib/python2.7/site-packages/twisted/internet/tcp.py:249:_dataReceived
/usr/lib/python2.7/site-packages/twisted/protocols/tls.py:315:dataReceived
--- <exception caught here> ---
/usr/lib/python2.7/site-packages/twisted/protocols/tls.py:235:_checkHandshakeStatus
/usr/lib/python2.7/site-packages/OpenSSL/SSL.py:1915:do_handshake
/usr/lib/python2.7/site-packages/OpenSSL/SSL.py:1647:_raise_ssl_error
/usr/lib/python2.7/site-packages/OpenSSL/_util.py:54:exception_from_error_queue
]`

**Comment by Schimmelreiter** [comment]
Probably incompatible or bad certs on those pages.
"downloadPage" probably needs some arguments to disable SSL cert verification (Which basically makes it as insecure as http again).

**Comment by davesayers2014** [comment]
> Probably incompatible or bad certs on those pages.
> "downloadPage" probably needs some arguments to disable SSL cert verification (Which basically makes it as insecure as http again).

The full code in my pr doesn't give the SSL errors. I think it's to do with SSL V3 disabled as cloudflare doesn't like it https://blog.cloudflare.com/sslv3-support-disabled-by-default-due-to-vulnerability/amp/

**Pull request closed without merging**
